blank_issues_enabled: true
contact_links:
  - name: ElevenSeventyFive Core Security Policy
    url: https://github.com/elevenseventyfive/elevenseventyfive/blob/master/SECURITY.md
    about: View security policy
  - name: ElevenSeventyFive Core Developers
    url: https://bitcoincore.org
    about: ElevenSeventyFive Core homepage
